
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: meatdoctor-ucc-backend
  annotations:
    description: "MeatDoctor UCC Backend API"
    tags: "nodejs,express,api"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${CONTEXT_DIR}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: nodejs:18-ubi8
        env:
        - name: NPM_MIRROR
          value: ${NPM_MIRROR}
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: Generic
      generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - name: ${NAME}
          image: " "
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: NODE_ENV
            value: "production"
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-url
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-key
          - name: SUPABASE_SERVICE_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-service-key
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: jwt-secret
          - name: HUBTEL_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-client-id
          - name: HUBTEL_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-client-secret
          - name: HUBTEL_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-sender-id
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: admin-email
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: admin-password
          - name: FRONTEND_URL
            value: "https://meatdoctorucc.netlify.app"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: ${NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
parameters:
- name: NAME
  displayName: Application Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: meatdoctor-ucc-backend
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
  value: https://github.com/yourusername/your-repo.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  value: main
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root of your repository.
  value: meatdoctorucc-backend
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: GENERIC_WEBHOOK_SECRET
  displayName: Generic Webhook Secret
  description: A secret string used to configure the Generic webhook.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: NPM_MIRROR
  displayName: Custom NPM Mirror URL
  description: The custom NPM mirror URL
  value: ""
