
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: meatdoctor-ucc-backend
  annotations:
    description: "MeatDoctor UCC Backend API"
    tags: "nodejs,express,api"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - name: ${NAME}
          image: ${IMAGE}
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: NODE_ENV
            value: "production"
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-url
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-key
          - name: SUPABASE_SERVICE_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-service-key
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: jwt-secret
          - name: HUBTEL_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-client-id
          - name: HUBTEL_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-client-secret
          - name: HUBTEL_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-sender-id
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: admin-email
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: admin-password
          - name: FRONTEND_URL
            value: "https://meatdoctorucc.netlify.app"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: ${NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
parameters:
- name: NAME
  displayName: Application Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: meatdoctor-ucc-backend
- name: IMAGE
  displayName: Docker Image
  description: The Docker image to deploy
  required: true
  value: your-registry/meatdoctor-ucc-backend:latest
