
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: meatdoctor-ucc-backend
  annotations:
    description: "MeatDoctor UCC Backend API"
    tags: "nodejs,express,api"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - name: ${NAME}
          image: ${IMAGE}
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: PORT
            value: "8080"
          - name: HOST
            value: "0.0.0.0"
          - name: NODE_ENV
            value: "production"
          - name: FRONTEND_URL
            value: "https://meatdoctorucc.netlify.app"
          # Optional environment variables - will be created from secrets if they exist
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-url
                optional: true
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-key
                optional: true
          - name: SUPABASE_SERVICE_KEY
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: supabase-service-key
                optional: true
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: jwt-secret
                optional: true
          - name: HUBTEL_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-client-id
                optional: true
          - name: HUBTEL_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-client-secret
                optional: true
          - name: HUBTEL_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: hubtel-sender-id
                optional: true
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: admin-email
                optional: true
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${NAME}-secrets
                key: admin-password
                optional: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
      app: ${NAME}
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
parameters:
- name: NAME
  displayName: Application Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: meatdoctor-ucc-backend
- name: IMAGE
  displayName: Docker Image
  description: The Docker image to deploy
  required: true
  value: image-registry.openshift-image-registry.svc:5000/officialjwise-dev/meatdoctor-ucc-backend:latest
